[window]
opacity = 0.8
padding = { x = 8, y = 8 }

[font]
size = 12.0
normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold = { family = "GeistMono Nerd Font", style = "Bold" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"
dim_foreground = "#a5adcb"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#f4dbd6"

[colors.selection]
text = "#cad3f5"
background = "#363a4f"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#a5adcb"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"
