[colors.primary]
background = '#eff1f5'
foreground = '#4c4f69'

[colors.selection]
text = '#4c4f69'
background = '#eadcff'

[colors.cursor]
text = '#eff1f5'
cursor = '#8839ef'

[colors.normal]
black = '#181825'
red = '#e3133a'
green = '#01b329'
yellow = '#ffbd00'
blue = '#8932fa'
magenta = '#dbc0ff'
cyan = '#8839ef'
white = '#403e42'

[colors.bright]
black = '#c6c3cb'
red = '#ff3c61'
green = '#29ff59'
yellow = '#ffbd00'
blue = '#9539ff'
magenta = '#dbc0ff'
cyan = '#c89dff'
white = '#faf7ff'
