#!/usr/bin/env bash
set -euo pipefail

lock_cmd='qs -c noctalia-shell ipc call lockScreen lock'

exec swayidle -w \
  before-sleep "$lock_cmd" \
  after-resume 'swaymsg "output * power on"' \
  timeout 300 'brightnessctl -s set 10' \
  resume 'brightnessctl -r' \
  timeout 330 "$lock_cmd" \
  timeout 350 'swaymsg "output * power off"' \
  resume 'swaymsg "output * power on"'
