general {
  lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
  before_sleep_cmd = qs -c noctalia-shell ipc call lockScreen lock
  after_sleep_cmd = niri msg action power-on-monitors
}

listener {
  timeout = 300
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

listener {
  timeout = 330
  on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  timeout = 350
  on-timeout = niri msg action power-off-monitors
  on-resume = niri msg action power-on-monitors
}

# listener {
#   timeout = 1800
#   on-timeout = systemctl suspend
# }
