wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/hypr/matterhorn.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = ~/.config/hypr/matterhorn-2.jpg
  fit_mode = cover
}

splash = false

