preload = ~/.config/hypr/scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama.png
preload = ~/.config/hypr/Pawel-Czerwinski-Abstract-Purple-Blue.jpg
preload = ~/.config/hypr/matterhorn.jpg

wallpaper = HDMI-A-1,~/.config/hypr/matterhorn.jpg
wallpaper = HDMI-A-2,~/.config/hypr/scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama.png

#enable splash text rendering over the wallpaper
splash = false

