# Catppuccin Latte (custom)

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#eff1f5"

# Main text color
theme[main_fg]="#4c4f69"

# Title color for boxes
theme[title]="#4c4f69"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8839ef"

# Background color of selected item in processes box
theme[selected_bg]="#ccd0da"

# Foreground color of selected item in processes box
theme[selected_fg]="#4c4f69"

# Color of inactive/disabled text
theme[inactive_fg]="#8c8fa1"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6c6f85"

# Cpu box outline color
theme[cpu_box]="#9ca0b0"

# Memory/disks box outline color
theme[mem_box]="#9ca0b0"

# Net up/down box outline color
theme[net_box]="#9ca0b0"

# Processes box outline color
theme[proc_box]="#9ca0b0"

# Box divider line and small boxes line color
theme[div_line]="#bcc0cc"

# Temperature graph colors
theme[temp_start]="#df8e1d"
theme[temp_mid]="#fe640b"
theme[temp_end]="#d20f39"

# CPU graph colors
theme[cpu_start]="#209fb5"
theme[cpu_mid]="#1e66f5"
theme[cpu_end]="#8839ef"

# Mem/Disk free meter
theme[free_start]="#40a02b"
theme[free_mid]=""
theme[free_end]="#40a02b"

# Mem/Disk cached meter
theme[cached_start]="#04a5e5"
theme[cached_mid]=""
theme[cached_end]="#04a5e5"

# Mem/Disk available meter
theme[available_start]="#179299"
theme[available_mid]=""
theme[available_end]="#179299"

# Mem/Disk used meter
theme[used_start]="#d20f39"
theme[used_mid]=""
theme[used_end]="#d20f39"

# Download graph colors
theme[download_start]="#04a5e5"
theme[download_mid]="#1e66f5"
theme[download_end]="#7287fd"

# Upload graph colors
theme[upload_start]="#df8e1d"
theme[upload_mid]="#fe640b"
theme[upload_end]="#e64553"
