# Catppuccin Mocha (custom)

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1e1e2e"

# Main text color
theme[main_fg]="#cdd6f4"

# Title color for boxes
theme[title]="#cdd6f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cba6f7"

# Background color of selected item in processes box
theme[selected_bg]="#313244"

# Foreground color of selected item in processes box
theme[selected_fg]="#cdd6f4"

# Color of inactive/disabled text
theme[inactive_fg]="#7f849c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a6adc8"

# Cpu box outline color
theme[cpu_box]="#6c7086"

# Memory/disks box outline color
theme[mem_box]="#6c7086"

# Net up/down box outline color
theme[net_box]="#6c7086"

# Processes box outline color
theme[proc_box]="#6c7086"

# Box divider line and small boxes line color
theme[div_line]="#45475a"

# Temperature graph colors
theme[temp_start]="#f9e2af"
theme[temp_mid]="#fab387"
theme[temp_end]="#f38ba8"

# CPU graph colors
theme[cpu_start]="#74c7ec"
theme[cpu_mid]="#89b4fa"
theme[cpu_end]="#cba6f7"

# Mem/Disk free meter
theme[free_start]="#a6e3a1"
theme[free_mid]=""
theme[free_end]="#a6e3a1"

# Mem/Disk cached meter
theme[cached_start]="#89dceb"
theme[cached_mid]=""
theme[cached_end]="#89dceb"

# Mem/Disk available meter
theme[available_start]="#94e2d5"
theme[available_mid]=""
theme[available_end]="#94e2d5"

# Mem/Disk used meter
theme[used_start]="#f38ba8"
theme[used_mid]=""
theme[used_end]="#f38ba8"

# Download graph colors
theme[download_start]="#89dceb"
theme[download_mid]="#89b4fa"
theme[download_end]="#b4befe"

# Upload graph colors
theme[upload_start]="#f9e2af"
theme[upload_mid]="#fab387"
theme[upload_end]="#eba0ac"
