# Catppuccin Macchiato (custom)

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#24273a"

# Main text color
theme[main_fg]="#cad3f5"

# Title color for boxes
theme[title]="#cad3f5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c6a0f6"

# Background color of selected item in processes box
theme[selected_bg]="#363a4f"

# Foreground color of selected item in processes box
theme[selected_fg]="#cad3f5"

# Color of inactive/disabled text
theme[inactive_fg]="#8087a2"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a5adcb"

# Cpu box outline color
theme[cpu_box]="#6e738d"

# Memory/disks box outline color
theme[mem_box]="#6e738d"

# Net up/down box outline color
theme[net_box]="#6e738d"

# Processes box outline color
theme[proc_box]="#6e738d"

# Box divider line and small boxes line color
theme[div_line]="#494d64"

# Temperature graph colors
theme[temp_start]="#eed49f"
theme[temp_mid]="#f5a97f"
theme[temp_end]="#ed8796"

# CPU graph colors
theme[cpu_start]="#7dc4e4"
theme[cpu_mid]="#8aadf4"
theme[cpu_end]="#c6a0f6"

# Mem/Disk free meter
theme[free_start]="#a6da95"
theme[free_mid]=""
theme[free_end]="#a6da95"

# Mem/Disk cached meter
theme[cached_start]="#91d7e3"
theme[cached_mid]=""
theme[cached_end]="#91d7e3"

# Mem/Disk available meter
theme[available_start]="#8bd5ca"
theme[available_mid]=""
theme[available_end]="#8bd5ca"

# Mem/Disk used meter
theme[used_start]="#ed8796"
theme[used_mid]=""
theme[used_end]="#ed8796"

# Download graph colors
theme[download_start]="#91d7e3"
theme[download_mid]="#8aadf4"
theme[download_end]="#b7bdf8"

# Upload graph colors
theme[upload_start]="#eed49f"
theme[upload_mid]="#f5a97f"
theme[upload_end]="#ee99a0"
