# Base background and font
color=eff1f5ff
font=monospace
font-size=16

# Indicator styling
indicator-radius=140
indicator-thickness=10
line-uses-ring

# Catppuccin Latte palette
inside-color=eff1f5cc
inside-ver-color=eff1f5cc
inside-wrong-color=eff1f5cc
ring-color=1e66f5ff
ring-ver-color=7287fdff
ring-wrong-color=d20f39ff
ring-clear-color=04a5e5cc
separator-color=00000000
text-color=4c4f69ff
text-ver-color=4c4f69ff
text-wrong-color=d20f39ff
key-hl-color=8839efff
bs-hl-color=d20f39ff
show-failed-attempts
